services:
  web-scrapper:
    container_name: web_scrapper
    image: jnstockley/web-scrapper:latest
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/:/web-scrapper/data/
    healthcheck:
      test: poetry run python3 src/healthcheck.py
      interval: 60s
      retries: 3
      start_period: 20s
      timeout: 10s
