services:
  web-scrapper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_scrapper_dev
    image: web-scrapper:dev
    env_file:
      - .env
    restart: no
    volumes:
      - ./data/:/web-scrapper/data/
    healthcheck:
      test: poetry run python3 src/main.py
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 30s