services:
  web-scrapper:
    container_name: web_scrapper_dev
    image: web-scrapper:dev
    working_dir: /web-scrapper
    env_file:
      - .env
    restart: always
    volumes:
      - ./config.toml:/web-scrapper/config.toml
      - ./data/:/web-scrapper/data/
